// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using QMS.Data;
using QMS.Models;
using System;

namespace QMS.Migrations.PatientDb
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20170908075131_PatientInitial")]
    partial class PatientInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("QMS.Models.Encounter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FHIR_id");

                    b.Property<DateTime?>("end");

                    b.Property<int>("patient_id");

                    b.Property<DateTime>("start");

                    b.Property<int>("status");

                    b.Property<int>("visitType");

                    b.HasKey("id");

                    b.HasIndex("patient_id");

                    b.ToTable("Encounter","public");
                });

            modelBuilder.Entity("QMS.Models.Patient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FHIR_id");

                    b.Property<bool>("HIVtest");

                    b.Property<bool>("IsPregnant");

                    b.Property<bool>("abused");

                    b.Property<bool>("active");

                    b.Property<string>("birthDate")
                        .IsRequired();

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("complaint")
                        .HasMaxLength(400);

                    b.Property<string>("email")
                        .IsRequired();

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("gender");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<bool>("lifethreatening");

                    b.Property<string>("line1")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("line2")
                        .HasMaxLength(40);

                    b.Property<string>("policy")
                        .HasMaxLength(50);

                    b.Property<string>("postalCode")
                        .IsRequired();

                    b.Property<int>("preferredGender");

                    b.Property<string>("prefgender");

                    b.Property<bool>("primary");

                    b.Property<string>("primaryName")
                        .HasMaxLength(50);

                    b.Property<bool>("primaryPhysician");

                    b.Property<string>("provider")
                        .HasMaxLength(50);

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<string>("telecom");

                    b.Property<bool>("travel");

                    b.Property<bool>("vaccines");

                    b.HasKey("id");

                    b.ToTable("Patient","public");
                });

            modelBuilder.Entity("QMS.Models.Encounter", b =>
                {
                    b.HasOne("QMS.Models.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
